#! /usr/bin/python3


import sys
lab10 = sys.argv[0]
arguments = sys.argv[1:]



count = len(arguments)

sum = 0

sum = sum +  len(arguments)

avg = sum / count


print ('The average of the', count, 'numbers is: ', avg   )






