#! /usr/bin/python3


import sys
lab10 = sys.argv[0]
arguments = sys.argv[1:]



count = len(arguments)

total = 0

for arg in sys.argv[1]:
	total = total + int(sys.argv[1])

avg = total / count


print ('The average of the', count, 'numbers is: ' , avg  )


 











